---
deployment:
  tasks:
    - export DEPLOYPATH=/home/joinmeus/public_html/tutor_laravel/
    - /bin/cp -r ./public/.* ./
    - /bin/rm -rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp -r .* $DEPLOYPATH