/*
-- Query: SELECT * FROM tutorspace_test.majors
LIMIT 0, 1000

-- Date: 2021-01-19 20:39
*/
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (1,'Accounting');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (2,'Acting for the Stage, Screen and New Media');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (3,'Aerospace Engineering');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (4,'American Popular Culture');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (5,'American Studies and Ethnicity (African American Studies)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (6,'American Studies and Ethnicity (Asian American Studies)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (7,'American Studies and Ethnicity');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (8,'American Studies and Ethnicity (Chicano/Latino Studies)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (9,'Animation and Digital Arts');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (10,'Anthropology');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (11,'Anthropology (Visual Anthropology)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (12,'Applied and Computational Mathematics');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (13,'Applied and Computational Mathematics');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (14,'Applied Mechanics');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (15,'Archaeology');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (16,'Architectural Studies');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (17,'Architecture');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (18,'Art');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (19,'Art History');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (20,'Arts, Technology and the Business of Innovation');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (21,'Astronautical Engineering');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (22,'Astronomy');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (23,'Astronomy');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (24,'Biochemistry');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (25,'Biological Sciences');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (26,'Biological Sciences');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (27,'Biomedical Engineering');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (28,'Biomedical Engineering, Electrical Engineering Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (29,'Biomedical Engineering, Mechanical Engineering Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (30,'Biomedical Engineering, Molecular and Cellular Engineering Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (31,'Biophysics');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (32,'Business Administration');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (33,'Business Administration (Cinematic Arts)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (34,'Business Administration (International Relations)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (35,'Business Administration (Real Estate Finance)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (36,'Business Administration (World Program)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (37,'Central European Studies');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (38,'Chemical Engineering');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (39,'Chemical Engineering, Biochemical Engineering Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (40,'Chemical Engineering, Environmental Engineering Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (41,'Chemical Engineering, Nanotechnology Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (42,'Chemical Engineering, Petroleum Engineering Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (43,'Chemical Engineering, Polymer/Materials Science Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (44,'Chemical Engineering, Sustainable Energy Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (45,'Chemistry');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (46,'Chemistry');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (47,'Chemistry (Chemical Biology)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (48,'Chemistry (Chemical Nanoscience)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (49,'Chemistry (Research)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (50,'Choral Music');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (51,'Choral Music');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (52,'Cinema and Media Studies');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (53,'Cinematic Arts, Film and Television Production');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (54,'Cinematic Arts, Film and Television Production');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (55,'Civil Engineering');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (56,'Civil Engineering, Building Science Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (57,'Civil Engineering, Construction Engineering and Management Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (58,'Civil Engineering, Environmental Engineering Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (59,'Civil Engineering, Structural Engineering Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (60,'Civil Engineering, Water Resources Engineering Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (61,'Classics');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (62,'Cognitive Science');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (63,'Communication');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (64,'Comparative Literature');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (65,'Composition');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (66,'Computational Linguistics');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (67,'Computational Neuroscience');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (68,'Computer Engineering and Computer Science');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (69,'Computer Science');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (70,'Computer Science (Games)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (71,'Computer Science/Business Administration');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (72,'Contemporary Latino and Latin American Studies');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (73,'Dance');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (74,'Data Science');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (75,'Dental Hygiene');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (76,'Design');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (77,'Earth Sciences');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (78,'East Asian Area Studies');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (79,'East Asian Languages and Cultures');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (80,'Economics');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (81,'Electrical and Computer Engineering');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (82,'English');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (83,'Environmental Engineering');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (84,'Environmental Science and Health');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (85,'Environmental Science and Health');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (86,'Environmental Studies');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (87,'Environmental Studies');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (88,'Fine Arts');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (89,'French');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (90,'Gender and Sexuality Studies');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (91,'GeoDesign');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (92,'Geological Sciences');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (93,'Global Geodesign');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (94,'Global Health Studies');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (95,'Global Studies');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (96,'Health and Human Sciences');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (97,'Health and Humanity');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (98,'Health Promotion and Disease Prevention Studies');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (99,'History');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (100,'History and Social Science Education');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (101,'Human Biology');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (102,'Human Biology');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (103,'Human Development and Aging');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (104,'Human Development and Aging, Health Science Track');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (105,'Human Development and Aging, Honors Programs');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (106,'Industrial and Systems Engineering');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (107,'Intelligence and Cyber Operations');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (108,'Interactive Entertainment');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (109,'International Relations');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (110,'International Relations (Global Business)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (111,'International Relations and the Global Economy');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (112,'Italian');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (113,'Jazz Studies');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (114,'Jewish Studies');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (115,'Journalism');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (116,'Latin American and Iberian Cultures, Media and Politics');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (117,'Law, History, and Culture');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (118,'Lifespan Health');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (119,'Linguistics');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (120,'Linguistics and Cognitive Science');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (121,'Mathematics');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (122,'Mathematics');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (123,'Mechanical Engineering');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (124,'Mechanical Engineering, Petroleum Engineering');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (125,'Media Arts and Practice');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (126,'Middle East Studies');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (127,'Music');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (128,'Music Industry');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (129,'Music Industry');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (130,'Music Production');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (131,'Musical Theatre');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (132,'Narrative Studies');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (133,'Neuroscience');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (134,'Neuroscience');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (135,'Non-Governmental Organizations and Social Change');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (136,'Occupational Therapy');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (137,'Performance (Classical Guitar)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (138,'Performance (Flute), (Oboe), (Clarinet), (Bassoon), (Saxophone), (French Horn), (Trumpet), (Trombone), (Tuba) or (Percussion)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (139,'Performance (Organ)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (140,'Performance (Piano)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (141,'Performance (Popular Music)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (142,'Performance (Studio Guitar)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (143,'Performance (Violin), (Viola), (Violoncello), (Double Bass) or (Harp)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (144,'Performance (Vocal Arts)');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (145,'Pharmacology and Drug Development');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (146,'Philosophy');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (147,'Philosophy and Physics');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (148,'Philosophy, Politics and Economics');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (149,'Philosophy, Politics and Law');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (150,'Physical Sciences');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (151,'Physical Sciences');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (152,'Physics');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (153,'Physics');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (154,'Physics/Computer Science');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (155,'Political Economy');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (156,'Political Science');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (157,'Psychology');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (158,'Public Policy');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (159,'Public Relations');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (160,'Quantitative Biology');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (161,'Real Estate Development');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (162,'Religion');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (163,'Russian');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (164,'Social Sciences, with an Emphasis in Economics');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (165,'Social Sciences, with an Emphasis in Psychology');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (166,'Sociology');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (167,'Spanish');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (168,'Theatre');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (169,'Theatre, Acting Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (170,'Theatre, Comedy Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (171,'Theatre, Design Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (172,'Theatre, Design Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (173,'Theatre, Sound Design Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (174,'Theatre, Stage Management Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (175,'Theatre, Technical Direction Emphasis');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (176,'Urban Studies and Planning');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (177,'Visual and Performing Arts Studies');
INSERT INTO tutorspace.majors (`id`,`major`) VALUES (178,'Writing for Screen and Television');
