/*
-- Query: SELECT * FROM tutorspace_test.minors
LIMIT 0, 1000

-- Date: 2021-01-19 20:38
*/
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (1,'3-D Animation in Cinematic Arts');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (2,'3-Dimensional Design');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (3,'3D Computer Graphics and Modeling');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (4,'Accounting');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (5,'Advertising');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (6,'American Popular Culture');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (7,'American Studies and Ethnicity');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (8,'Animation and Digital Arts');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (9,'Applied Analytics');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (10,'Applied Computer Security');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (11,'Arabic');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (12,'Archaeology');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (13,'Archaeology of California');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (14,'Architecture');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (15,'Art History');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (16,'Astronautical Engineering');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (17,'Astronomy');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (18,'Behavioral Economics');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (19,'Biotechnology');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (20,'Blockchain');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (21,'Business Economics');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (22,'Business Finance');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (23,'Business Law');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (24,'Business');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (25,'Business Technology Fusion');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (26,'Ceramics');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (27,'Chemistry');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (28,'Chinese for the Professions');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (29,'Choreography for Stage and Screen');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (30,'Cinema-Television for the Health Professions');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (31,'Cinematic Arts');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (32,'Classical Greek');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (33,'Classical Perspectives');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (34,'Classics');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (35,'Comedy (Performance)');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (36,'Comedy');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (37,'Communication Design');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (38,'Communication Policy and Law');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (39,'Communication Technology Practices and Platforms');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (40,'Comparative Literature');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (41,'Computational Biology and Bioinformatics');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (42,'Computer and Digital Forensics');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (43,'Computer Programming');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (44,'Computer Science');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (45,'Connected Devices and Making');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (46,'Construction Planning and Management');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (47,'Construction Planning and Management Minor (Public Policy)');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (48,'Consumer Behavior Interdisciplinary');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (49,'Consumer Behavior');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (50,'Contemplative Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (51,'Craniofacial and Dental Technology');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (52,'Critical Approaches to Leadership');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (53,'Cultural Anthropology');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (54,'Cultural Competence in Medicine');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (55,'Cultural Diplomacy');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (56,'Cultural Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (57,'Culture, Media and Entertainment');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (58,'Cultures and Politics of the Pacific Rim');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (59,'Dance in Entertainment');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (60,'Dance');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (61,'Designing for Experiences');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (62,'Digital Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (63,'Disruptive Innovation');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (64,'Documentary');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (65,'Drawing');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (66,'Dynamics in Workplace Communication');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (67,'Early Modern Studies Interdisciplinary');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (68,'Earth Sciences Minor: Climate Change, Stewardship and Resiliency');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (69,'East Asian Area Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (70,'East Asian Languages and Cultures');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (71,'Economics');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (72,'Education and Society');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (73,'Engineering Management');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (74,'English');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (75,'Enterprise Information Systems');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (76,'Entertainment Industry');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (77,'Entrepreneurship');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (78,'Environmental Chemistry and Sustainability');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (79,'Environmental Health');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (80,'Environmental Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (81,'Ethics and Moral Philosophy');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (82,'Folklore and Popular Culture');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (83,'Food and Society');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (84,'Forensics and Criminality');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (85,'Foundations of Data Science');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (86,'French');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (87,'Future Cinema');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (88,'Game Animation');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (89,'Game Audio');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (90,'Game Design');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (91,'Game Entrepreneurism');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (92,'Game Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (93,'Game User Research');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (94,'Gender and Sexuality Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (95,'Gender and Social Justice');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (96,'Geobiology');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (97,'Geohazards');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (98,'German Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (99,'GIS and Sustainability Science');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (100,'Global Communication');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (101,'Global Health');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (102,'Health Administration');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (103,'Health Care Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (104,'Health Communication');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (105,'Health Innovation');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (106,'Health Policy');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (107,'Hip Hop, Street and Social Dance Forms');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (108,'History and Culture of Business');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (109,'History');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (110,'Human Movement Sciences');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (111,'Human Resource Management');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (112,'Human Rights');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (113,'Human Security and Geospatial Intelligence');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (114,'Immersive Media');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (115,'Individuals, Societies and Aging');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (116,'Innovation: The Digital Entrepreneur');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (117,'Intermedia Arts');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (118,'International Health, Development, and Social Justice Interdisciplinary');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (119,'International Policy and Management');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (120,'International Relations');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (121,'Internet of Things Engineering');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (122,'Iranian Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (123,'Italian');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (124,'Jazz Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (125,'Jewish American Studies Minor (American Studies)');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (126,'Jewish American Studies Minor (Jewish Studies)');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (127,'Jewish Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (128,'Judaic Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (129,'Justice, Voice, and Advocacy');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (130,'Korean Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (131,'Landscape Architecture');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (132,'Latin American Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (133,'Latin');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (134,'Law and Public Policy');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (135,'Law and Society');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (136,'Legal Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (137,'LGBTQ Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (138,'Linguistics');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (139,'Luso-Brazilian Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (140,'Management Consulting');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (141,'Managing Human Relations');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (142,'Marine Biology');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (143,'Marketing');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (144,'Mathematical Finance');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (145,'Mathematics');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (146,'Media and Social Change');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (147,'Media Economics and Entrepreneurship');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (148,'Medical Anthropology');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (149,'Middle East Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (150,'Mobile App Development');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (151,'Modern Art Markets and Ethics');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (152,'Multimedia for Designers and Entrepreneurs');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (153,'Music Industry');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (154,'Music Production');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (155,'Music Recording');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (156,'Musical Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (157,'Musical Theatre');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (158,'Nanotechnology');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (159,'Native American Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (160,'Natural Science');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (161,'Neuroscience');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (162,'News Media and Society');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (163,'Nonprofits, Philanthropy and Volunteerism Interdisciplinary');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (164,'Nonprofits, Philanthropy and Volunteerism');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (165,'Nutrition and Health Promotion');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (166,'Occupational Science');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (167,'Operations and Supply Chain Management');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (168,'Organizational Leadership and Management');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (169,'Painting');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (170,'Performance Science');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (171,'Performing Arts Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (172,'Performing Leadership');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (173,'Performing Social Change');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (174,'Petroleum Engineering');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (175,'Philosophy for Business, Law, and the Professions');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (176,'Philosophy');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (177,'Photography and Social Change');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (178,'Photography');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (179,'Physics');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (180,'Playwriting');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (181,'Political Organizing in the Digital Age');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (182,'Political Science');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (183,'Popular Music Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (184,'Practical Politics');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (185,'Product Design');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (186,'Professional and Managerial Communication');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (187,'Psychology and Law');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (188,'Psychology');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (189,'Public Health');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (190,'Public Relations');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (191,'Race, Ethnicity and Politics');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (192,'Real Estate Development');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (193,'Real Estate Finance');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (194,'Religion');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (195,'Resistance to Genocide Interdisciplinary');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (196,'Risk Management');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (197,'Russian Area Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (198,'Russian');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (199,'Science and Management of Biomedical Therapeutics');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (200,'Science Visualization');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (201,'Science, Health and Aging');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (202,'Screenwriting');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (203,'Sculpture');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (204,'Social Entrepreneurship');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (205,'Sociology');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (206,'Songwriting');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (207,'Southeast Asia and its People');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (208,'Spanish');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (209,'Spatial Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (210,'Sports Business and Management');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (211,'Sports Media Industries');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (212,'Sports Media Studies Minor ');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (213,'Statistics');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (214,'Substance Abuse Prevention');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (215,'Teaching English to Speakers of Other Languages (TESOL)');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (216,'Technology Commercialization');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (217,'The Dynamics of Early Childhood');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (218,'Theatre');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (219,'Thematic Approaches to Humanities and Society');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (220,'Themed Entertainment');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (221,'Two-Dimensional Studies');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (222,'Urban Sustainable Planning');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (223,'User Experience');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (224,'Video Game Design and Management');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (225,'Video Game Programming');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (226,'Visual Culture');
INSERT INTO tutorspace.minors (`id`,`minor`) VALUES (227,'Web Technologies and Applications');

